// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAlcC3GMgeFgLsKXp0ubdU_Kwefa3F3LA',
    appId: '1:90782672853:web:6b79a6ae2900fa6087ff5c',
    messagingSenderId: '90782672853',
    projectId: 'tasqrauth',
    authDomain: 'tasqrauth.firebaseapp.com',
    storageBucket: 'tasqrauth.appspot.com',
    measurementId: 'G-TQ89BBZ0SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUvxATd2kOZa3IpiHVk4T7uUi-gdP86gU',
    appId: '1:90782672853:android:07e4bed3e20fb3e087ff5c',
    messagingSenderId: '90782672853',
    projectId: 'tasqrauth',
    storageBucket: 'tasqrauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPn_CDMwsAVdHorIzSLy8REP_8h9mzKb8',
    appId: '1:90782672853:ios:bc986a89bf94bc9c87ff5c',
    messagingSenderId: '90782672853',
    projectId: 'tasqrauth',
    storageBucket: 'tasqrauth.appspot.com',
    iosClientId: '90782672853-v14jegq1urdf31ma20ga4sep8ter4mns.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasqrauth',
  );
}
